### PR TITLE
Homework for Git week1

### PR DESCRIPTION
**Pull request by natata08**
I added three files: my_favorite_food.txt, my_second_favorite_food.txt and  countries.txt.

### CODE REVIEW

**Review by jason-vasilev — COMMENTED** [review]
Excellent, Natalia. Could you add one more country to the list of `countries.txt` just so you can see how the PR changes?

**Comment by natata08** [comment]
> Excellent, Natalia. Could you add one more country to the list of `countries.txt` just so you can see how the PR changes?

Yasen, I've done it.

**Review by jason-vasilev — APPROVED** [review]

**Comment by jason-vasilev** [comment]
Great! You are welcome to merge now (:

**Comment by natata08** [comment]
Thank you!

**Pull request merged**
